repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
        additional_dependencies: []
  - repo: local
    hooks:
      - id: blacklist-patterns
        name: Check for blacklisted secret patterns
        entry: python -c "import re, sys, pathlib; pattern = re.compile(r'(?:password|secret|api[_-]?key|token|bearer)\\s*[:=]\\s*(?:[\'\"]?)[^\s\'\"]{12,}', re.IGNORECASE); violations = [];\nfor path in map(pathlib.Path, sys.argv[1:]):\n    text = path.read_text(errors='ignore');\n    for lineno, line in enumerate(text.splitlines(), 1):\n        if pattern.search(line):\n            violations.append(f"{path}:{lineno}: potential secret")\nif violations:\n    print('\n'.join(violations));\n    sys.exit(1)"
        language: system
        files: .
        pass_filenames: true
        types: [text]
