openapi: 3.0.3
info:
  title: One Ledger — Six Registers API
  version: "0.1.0"
paths:
  /api/people:
    get:
      summary: List people
      responses:
        "200":
          description: OK
    post:
      summary: Create person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                thar: { type: string }
                phone: { type: string }
                email: { type: string, format: email }
              required: [name]
      responses:
        "201":
          description: Created
