name: Secret Scans

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # required for PRs
        with:
          config-path: .gitleaks.toml
          redact: true
          fail-on-detection: true

  secretlint:
    name: Secretlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Secretlint
        run: |
          npx -y \
            --package=secretlint \
            --package=@secretlint/secretlint-rule-preset-recommend \
            secretlint --format stylish .

  trufflehog:
    name: TruffleHog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # PR: scan only changes since base using the v3 CLI (Docker image)
      - name: Run TruffleHog on PR diff (v3)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker://ghcr.io/trufflesecurity/trufflehog:latest
        with:
          args: >
            git
            --since-commit="${{ github.event.pull_request.base.sha }}"
            --results=verified
            --exclude-paths=.trufflehogignore
            --fail
            file://$GITHUB_WORKSPACE

      # Push: scan recent history on the current branch
      - name: Run TruffleHog on current branch (v3)
        if: ${{ github.event_name == 'push' }}
        uses: docker://ghcr.io/trufflesecurity/trufflehog:latest
        with:
          args: >
            git
            --branch="${{ github.ref_name }}"
            --max-depth=200
            --results=verified
            --exclude-paths=.trufflehogignore
            --fail
            file://$GITHUB_WORKSPACE
